### ISSUE TITLE
Enable more flags

### ISSUE THREAD

**Issue by romac** [SpinResearch/merkle.rs#10]
For example:

```rust
#![deny(
    missing_docs,
    missing_debug_implementations, missing_copy_implementations,
    trivial_casts, trivial_numeric_casts,
    unsafe_code, unstable_features,
    unused_import_braces, unused_qualifications
)]
```

https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/

**Comment by romac** [comment]
Feel free to suggest more flags to enable.

**Comment by romac** [comment]
We might also want to enable [clippy](https://github.com/Manishearth/rust-clippy), and a [badge](https://clippy.bashy.io/) to the README.

**Comment by FredericJacobs** [comment]
Upon further review, we decided to adopt `rust-clippy` and current flags are sufficient.
