### ISSUE TITLE
Remove Hashable to use Into

### ISSUE THREAD

**Issue by FredericJacobs** [SpinResearch/merkle.rs#2]
[Reference](https://doc.rust-lang.org/nightly/////std/convert/trait.Into.html)

**Comment by romac** [comment]
Should be fairly straightforward given that

``` rust
impl<T, U> Into<U> for T where U: From<T>
```

and

``` rust
impl<'a, T> From<Cow<'a, [T]>> for Vec<T> where [T]: ToOwned<Owned=Vec<T>>
```

**Comment by romac** [comment]
Since there are no appropriate `From` instance for plain `u8`, I changed the tests to work with values of type `Vec<u8>` (which is what `merkle_signing` will use anyway). It works out of the box for `Vec<u8>` and `String`.

**Comment by romac** [comment]
Now that I think about it, I should have checked what happens with slices (and thus kept that commit in its own branch). Anyway, feel free to re-open if needed.

**Comment by FredericJacobs** [comment]
LGTM 👍

**Comment by romac** [comment]
Just rebased `proof` on top of that.

**Comment by FredericJacobs** [comment]
Cool, just don't miss my comment

https://github.com/SpinResearch/merkle.rs/pull/1#pullrequestreview-8638872

**Comment by romac** [comment]
I was just reading it :)
