### ISSUE TITLE
Generate proof by index.

### ISSUE THREAD

**Issue by afck** [SpinResearch/merkle.rs#31]
[`MerkleTree::gen_proof`](https://docs.rs/merkle/1.5.0/merkle/struct.MerkleTree.html#method.gen_proof) takes a leaf value and returns a proof for it, but if the value occurs more than once, the user can't specify which proof they want. It would be useful to have a method that returns the proof for the `n`-th leaf, by index. I'd be happy to try and write code for that, if you are okay with it.

We are using it in `hbbft` and are currently working around the limitation by making the leafs unique (prepending an index byte), which is wasteful. Conversely, we compute the index from the proof here, which might also make sense as a method of `Lemma`:
https://github.com/poanetwork/hbbft/blob/71fa32c18f977c45e7869d47e50b4eccfd61d898/src/broadcast.rs#L493

**Comment by romac** [comment]
That is indeed an oversight on our part! I'd be happy to review and merge a PR for that, so go ahead if you feel like it :)
