### ISSUE TITLE
Protobuf 1.7 broke master again

### ISSUE THREAD

**Issue by psivesely** [SpinResearch/merkle.rs#39]
Obviously they're not too keen on proper use of semver. I think we should use [Tilde requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements) for rust-protobuf because even after merging #38 we should expect to continue dealing with this problem.

**Comment by psivesely** [comment]
One thing I'm noticing on my system is that cargo is pullling in 1.7.1 when I specify version `^1.6.x` or `~1.7.1`, however, a 1.7.3 release exists and according to Rust documentation on specifying dependencies, this is the one that should be brought in.

**Comment by afck** [comment]
Did you do `cargo update`? If there's a `Cargo.lock` it doesn't try to download newer versions.

**Comment by psivesely** [comment]
> Did you do cargo update? If there's a Cargo.lock it doesn't try to download newer versions.

Yeah, I forgot that, thanks. Anyway, broken with 1.7.3 as well.
